#!/bin/bash
touch .env
echo AZURE_AD_CLIENT_ID=$AZURE_AD_CLIENT_ID >>.env
echo AZURE_AD_CLIENT_SECRET=$AZURE_AD_CLIENT_SECRET >>.env
echo AZURE_AD_TENANT_ID=$AZURE_AD_TENANT_ID >>.env
echo NEXTAUTH_SECRET=$NEXTAUTH_SECRET >>.env
echo NEXTAUTH_URL=$NEXTAUTH_URL >>.env
echo PORT=3000 >>.env
echo API_BASE_URL=$API_BASE_URL >>.env
echo NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL >>.env
echo SERVICE_URL=$SERVICE_URL >>.env
echo NEXT_PUBLIC_SERVICE_URL=$NEXT_PUBLIC_SERVICE_URL >>.env
echo NEXT_PUBLIC_GRAPH_BASE_URL=$NEXT_PUBLIC_GRAPH_BASE_URL >>.env
